sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
  - 2.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Installs bundler 2.0

before_install:
  - gem install bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.

jobs:
  include:
    - stage: deploy
      if: (tag IS blank)
      script:
        - bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
        - bundle exec htmlproofer ./_site
          --allow-missing-href
          --allow-hash-href
          --check-favicon
          --check-html
          --disable-external
      deploy: &firebase
        provider: firebase
        project: "staging"
        message: "travis deployed build $TRAVIS_BUILD_NUMBER for $TRAVIS_TAG ($TRAVIS_COMMIT)"
        token:
          secure: "seXu+j7TlwKyWqoMLB5O7ALI6XRAqxrXJkMe0hhf3FGIkdBLmx5MJSxXZR7D8DRww3wqqWtvTqNHPlJ4xx3emk4Y8pJqyRPQosjxOz4qfdxVEU669ia69qZ84JhM6jjVeHIcUU8J6NVkJF0H+Sn6S6+AkcR85EytsTUniONwTKeQHLZ61/x+UjqEW5dCB/S/iI1Np5FT2ep1dMthf3JeQxoEBSy739N9BILh7PYcuKb78ygB/cpdetiIlI8kKXV3pDV+Fb6HW+lSXrRa771Ngih95XMAYaED75KsxJajebLu0zKBvxs3muf0mz3Z39ivw/UEeQymPeXOZgNbU2A4yi4elFxGF7LnyaR+2FXVpX7hEgMA+oo2kkAF4EzOvy4vSzSXz2ANBQRAQYUc8iLR8e8UrPZnI3/836zDzKvJt8Tywt8aTYw/o15neXq60LSpns/aIwaZRvIeh0v3Upxl+TLpJiQvrtj9IDPvfHnh46Ky6Uzh3ahmtF06Y5iOwKlSgXp6Z0zV0J+OyYZ/kZCCMKSLDQ1N8oby1t0DNuLegL3VXTe6jiym7zxqCdf9wIbQNKDW11R07d1v90N+MQiDoQEOUphFSrL9ep2yCMLFANTJMIiGGl7b9g9nXVdcjOouxbYZsGtjKfmnrz66c1ZtsHvFUkHXtBHcIeR8Nt8Jwls="
        on:
          branch:
           - master
          tags: false
        skip_cleanup: true # otherwise Travis CI will delete all the files created during the build
    - stage: deploy
      if: (tag IS present)
      script:
        - JEKYLL_ENV=production bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
        - bundle exec htmlproofer ./_site
          --allow-hash-href
          --check-favicon
          --check-html
          --disable-external
      deploy:
        <<: *firebase
        project: "default"
        on:
          tags: true

cache: bundler

notifications:
  slack:
    secure: "UBopf187EAleR/Yl8AtTqmafQ4v0RWLxcXj6Xp7/mTBt9urD4ZLBj8mQHmTUlhGLSnUqeKJjKXpf6cRrPpVLvkWIo4bdW998G0lQep3jPNj7qhIBuM5FnE9U2FMaS0vtPJqHqlDYkPuhfnNFuLXe8860ZrlsCzN3jBK+iUTJggMSaaqkRP4ot/M04QBxMlMCoglPh14k80Rxzo5oxzcrTqHz9B6St0OLLVy0CNifu6qaZp9esidyR/sX9dsaMianMfSX2MjDPPcUZFe893hvyJj9+znAiU3izrePZNcZrjHeUpf0CIUuArO5OikpC+g/aLrdxEVaZhQw0EppFzgxy2dDKiGRZ49gUe1ObOl8YSD/uZor/KSkNsJgNHqV2AIXMAw6Dnj9gXpJCK2L0qvLdbfRbXOpHHBSTEh49Uv90X0n7y0tLipShkYWDlQKtzSKBjnTYZp4E9SHqf4G1j9vEvU2oQ5EpEMaYFXyGgKF/gQjw/AV2JqAr9zJSOKgHvL0Pf/i3bwjZUx6CAejkdlZoeS/aNunqVwyJoKqjfFuN6xkvPukZz6Q3oSpfmjEajmfr5OuKARTPiTcq2bs71SZYKpIQpE5Dt8wdIZBMwRz5kvEVx4AfSIkEFMzfr1NK0vW3XgV0NDbXkcLEeyRhLkNe7EdAAUaTtrAsAUwV2D90Hg="
  email: false
