sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
  - 2.4.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.

stages:
  - name: buildAndDeploy
    if: tag IS blank
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: buildAndDeploy
      if: tag IS blank
      script:
        - JEKYLL_ENV=production
          bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
        - bundle exec htmlproofer ./_site
          --allow-missing-href
          --allow-hash-href
          --check-favicon
          --check-html
          --disable-external
      deploy: &firebase
        provider: firebase
        project: "staging"
        message: "travis ci deployed build \#$TRAVIS_BUILD_NUMBER for $TRAVIS_TAG ($TRAVIS_COMMIT)"
        token:
          secure: cHJkMVb1WO/SNzb6PvTZoB8ixNRArbLf5O0wB7ybQP1MiZ1i1SROsWK05kyubNIFbwT1aABrx3+pB/1xl2faAw1SXao9n+i2i2rqZvevVi8G/ohWrkKeh1S6Fi45OnEPjGkPGCIDfs14TJNwG43L7OFNlfJgMp6GntdLPgzmzU8IJq8mIWFK5QMd+cSSVDj8wJMmSvngV6ZDLCP4q7/HNuFSvzQh74F9hmFQLYZDaxnmkSovF9Qehyf+87o1BCirnLEJ8+zecGcaDbthzxtUhmcCQE1TV1y41/q8rXaLMyJDAB8TWevCNPRK0bTduOJzhFvfP+xDu5ZhrNPuuAR0HlzPAy+PS6Y+EQDy14yRvNkHrng0uRI6RAV/D43p+Dt4kffsy8SB3osrj4C/64GBpI9M0sH6X969bju8FRPPuOUr6sGydkvkkRuKGlSwFxXwF+77TuMGZFKxcFDztNHWp1991rYMO/qZLZGlk8DQHT8Gs2e+5Q9KeQrqJAlI9flJGPPGyqBLTc5sgc/vzr6CJHmGXnSB8WI0mwJVrdUyzdJjbN4KQm1A1u79PbWHfQ/ucEV+SmhJqm7uKintUFuZDtVZctcwLYAC3LXRum1KIJgLjgwxfW1xczPa6txY4KvVyn3v2E4V9I3We//RfTam+1ZjNZp8Y6gBlfvB9xW/rsM=
        on:
          branch:
           - master
           - develop
          tags: false
        skip_cleanup: true # otherwise Travis CI will delete all the files created during the build
    - stage: release
      script:
        - JEKYLL_ENV=production
          bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
        - bundle exec htmlproofer ./_site
          --allow-missing-href
          --allow-hash-href
          --check-favicon
          --check-html
          --disable-external
      deploy:
        <<: *firebase
        project: "default"
        on:
          tags: true

cache: bundler

notifications:
  slack:
    secure: "UBopf187EAleR/Yl8AtTqmafQ4v0RWLxcXj6Xp7/mTBt9urD4ZLBj8mQHmTUlhGLSnUqeKJjKXpf6cRrPpVLvkWIo4bdW998G0lQep3jPNj7qhIBuM5FnE9U2FMaS0vtPJqHqlDYkPuhfnNFuLXe8860ZrlsCzN3jBK+iUTJggMSaaqkRP4ot/M04QBxMlMCoglPh14k80Rxzo5oxzcrTqHz9B6St0OLLVy0CNifu6qaZp9esidyR/sX9dsaMianMfSX2MjDPPcUZFe893hvyJj9+znAiU3izrePZNcZrjHeUpf0CIUuArO5OikpC+g/aLrdxEVaZhQw0EppFzgxy2dDKiGRZ49gUe1ObOl8YSD/uZor/KSkNsJgNHqV2AIXMAw6Dnj9gXpJCK2L0qvLdbfRbXOpHHBSTEh49Uv90X0n7y0tLipShkYWDlQKtzSKBjnTYZp4E9SHqf4G1j9vEvU2oQ5EpEMaYFXyGgKF/gQjw/AV2JqAr9zJSOKgHvL0Pf/i3bwjZUx6CAejkdlZoeS/aNunqVwyJoKqjfFuN6xkvPukZz6Q3oSpfmjEajmfr5OuKARTPiTcq2bs71SZYKpIQpE5Dt8wdIZBMwRz5kvEVx4AfSIkEFMzfr1NK0vW3XgV0NDbXkcLEeyRhLkNe7EdAAUaTtrAsAUwV2D90Hg="
  email: false
