# Site settings
title: Dr. Selwicka-Wienerroither
description: Ärztin für Allgemeinmedizin
email: ordination.selwicka@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.selwicka-wienerroither.com" # the base hostname & protocol for your site
timezone: Europe/Vienna

plugins:
  - jekyll-maps
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

# Build settings
markdown: kramdown
sass:
  style: compressed

maps:
  google:
    api_key: AIzaSyB8T90B3L1At6r1NMNy3tkOSgQGkxn52sc

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-120166913-1      # Required - replace with your tracking id
    anonymizeIp: true       # Optional - Default: false - set to true for anonymized tracking

# Exclude files when building the site
exclude: ["backup", "vendor", "Gemfile", "README.md", "firebase.json",".idea", "page_demo.html"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: [p, li, td]
  profile: false

social:
  email: /kontakt/
  linkedin: https://www.linkedin.com/in/beate-selwicka-wienerroither-b5083281/
  google: https://www.google.at/maps/place/Dr.+Selwicka-Wienerroither/@48.2435459,16.3244421,15z/data=!4m2!3m1!1s0x0:0xa2b1b4659139977a?sa=X&ved=0ahUKEwi9mIPUva_bAhUEfMAKHV6ADHwQ_BIIeTAK
  #twitter: https://twitter.com/<username>
