# Site settings
title: Dr. med. Selwicka-Wienerroither
description: Ärztin für Allgemeinmedizin
landing_page_title: Wahlarztordination Dr. med. Selwicka-Wienerroither
email: ordination.selwicka@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://selwicka-wienerroither.com" # the base hostname & protocol for your site
timezone: Europe/Vienna
lang: de_AT
lang_only: de
theme_color: "#18202a" #chrome for android will color the url bar with this

plugins:
  - jekyll-analytics
  - jekyll-smartify #curly quotes
  - jekyll_version_plugin
  - jekyll-minifier
  - jekyll-webp
  - jekyll-last-modified-at
  - jekyll-sitemap

# Build settings
markdown: kramdown

sass:
  style: compressed

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-120166913-1      # Required - replace with your tracking id
    anonymizeIp: true       # Optional - Default: false - set to true for anonymized tracking

google_site_verification: ZT_IXc8gKvrNUoOkEXboZPweKbJzrFpzg5nCl4FMAiQ

# Exclude files when building the site
exclude: ["backup", "vendor", "Gemfile", "README.md", "firebase.json",".idea"]

social:
  name: Beate Selwicka-Wienerroither
  links:
    - https://www.linkedin.com/in/beate-selwicka-wienerroither-b5083281/

theme_social:
  email: /kontakt/
  linkedin: https://www.linkedin.com/in/beate-selwicka-wienerroither-b5083281/
  google: https://www.google.at/maps/place/Dr.+Selwicka-Wienerroither/@48.2435459,16.3244421,15z/data=!4m2!3m1!1s0x0:0xa2b1b4659139977a?sa=X&ved=0ahUKEwi9mIPUva_bAhUEfMAKHV6ADHwQ_BIIeTAK
  #twitter: https://twitter.com/<username>

jekyll-minifier:
  exclude: '**.*'

webp:
  enabled: true
  quality: 80
  img_dir: ["/images"]
  formats: [".jpeg", ".jpg"]
  gifs: [".gif"]
  regenerate: false
  exclude: ['banner2.jpg', 'banner2_blur.jpg']
