# Site settings
title: Dr. Selwicka-Wienerroither
description: Ärtztin für Allgemeinmedizin
owner: Ordination Selwicka-Wienerroither # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: ordination.selwicka@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.selwicka-wienerroither.com" # the base hostname & protocol for your site

contact:
  name: Dr. Beate Selwicka-Wienerroither
  address:
    line1: Krottenbachstrasse 110/11
    line2: Eingang Silvaraweg 2
    line3: 1190 Wien
  tel: +43 1 320 1543
  fax: +43 1 328 13 80

hours:
  day1:
   name: Montag
   time: 13:00 bis 18:00
  day2:
   name: Dienstag & Donnerstag
   time: 08:00 bis 11:00
  day3:
   name: Mittwoch
   time: 15:00 bis 19:00
  day4:
   name: Freitag
   time: 13:00 bis 16:00

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-maps
  - jekyll-seo-tag
  - jekyll-sitemap

maps:
  google:
    api_key: AIzaSyAKuz9MseFGG_XrNMVQD8YI5pRmMypDFf8

# Exclude files when building the site
exclude: [backup, vendor]

social:
  linkedin-square: https://www.linkedin.com/in/beate-selwicka-wienerroither-b5083281/
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon: