name: Build Site and Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '28 4 * * SUN,TUE,THU' # run 2:14 am every day

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

jobs:
  build_and_deploy:
    name: Build Site and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build Site with Jekyll (production)
        if: github.ref == 'refs/heads/main'
        run: JEKYLL_ENV=production bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
      - name: Build Site with Jekyll (development)
        if: github.event_name == 'pull_request'
        run: bundle exec jekyll build -t --config "_config.yml,_config.prod.yml"
      - name: Run htmlproofer
        run: |
          bundle exec htmlproofer ./_site --allow-missing-href --allow-hash-href --ignore-status-codes 301,302,999 --ignore_urls "https://www.linkedin.com/in/beate-selwicka-wienerroither-b5083281/"
      - name: Deploy Cloudflare Worker
        id: cloudflare-deploy-prod
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          accountId: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          command: deploy --config=wrangler.jsonc
